[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "UpliftGames/wally@0.3.1"
stylua = "JohnnyMorganz/stylua@2.0.2"
moonwave = "evaera/moonwave@1.2.1"
lune = "lune-org/lune@0.8.9"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
darklua = "seaofvoices/darklua@0.15.0"
